# Generated by Django 3.2.7 on 2021-12-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='profile_photo/avatar.png', upload_to='profile_photo/'),
        ),
    ]
